/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package restaurantmanagement;
 
import javax.swing.JOptionPane;
import java.io.File;
import java.util.Scanner;
import javax.swing.JFrame;

/**
 *
 * @author PC
 */
public class Admin_login extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(Admin_login.class.getName());

    /**
     * Creates new form Employee_login
     */
    public Admin_login() {
        initComponents();
         setLocationRelativeTo(null);
          setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        idlable = new javax.swing.JLabel();
        fid = new javax.swing.JTextField();
        Namelable = new javax.swing.JLabel();
        fName = new javax.swing.JTextField();
        BtnSubmit = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 153, 204));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Log In");

        idlable.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        idlable.setForeground(new java.awt.Color(0, 153, 204));
        idlable.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        idlable.setText("Id");

        fid.addActionListener(this::fidActionPerformed);

        Namelable.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        Namelable.setForeground(new java.awt.Color(0, 153, 204));
        Namelable.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Namelable.setText("Name");

        fName.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        fName.addActionListener(this::fNameActionPerformed);

        BtnSubmit.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        BtnSubmit.setText("Submit");
        BtnSubmit.addActionListener(this::BtnSubmitActionPerformed);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 294, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(70, 70, 70)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(idlable, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(fid, javax.swing.GroupLayout.DEFAULT_SIZE, 156, Short.MAX_VALUE)
                            .addComponent(Namelable, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(fName)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(106, 106, 106)
                        .addComponent(BtnSubmit)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(idlable)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(fid, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(Namelable)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(fName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(BtnSubmit, javax.swing.GroupLayout.DEFAULT_SIZE, 36, Short.MAX_VALUE)
                .addGap(15, 15, 15))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void fNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fNameActionPerformed
      
    }//GEN-LAST:event_fNameActionPerformed

    private void fidActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fidActionPerformed
        
    }//GEN-LAST:event_fidActionPerformed

    private void BtnSubmitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnSubmitActionPerformed
         String sid = fid.getText();
        String name=fName.getText();
        if ((name + "").isEmpty()) {
                JOptionPane.showMessageDialog(this, "Please, enter Admin name");
            }
          if(!sid.matches("\\d+")){
              JOptionPane.showMessageDialog(this, "ID must be contain only numbers");
        }
        else{
        int id=Integer.parseInt(sid); 
            goToPageIfFound(id);}       
    }//GEN-LAST:event_BtnSubmitActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(() -> new Admin_login().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BtnSubmit;
    private javax.swing.JLabel Namelable;
    private javax.swing.JTextField fName;
    private javax.swing.JTextField fid;
    private javax.swing.JLabel idlable;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
public void goToPageIfFound(int id) {
    String fileName = "admin.txt";

    try (Scanner sc = new Scanner(new File(fileName))) {
        while (sc.hasNextLine()) {
            String line = sc.nextLine();
            String[] parts = line.split(",");

            if (parts.length > 0) {
                int currentId = Integer.parseInt(parts[0].trim());

                if (currentId == id) {
                    this.dispose();
                    java.awt.EventQueue.invokeLater(() -> {
            AdminDashboard x = new AdminDashboard();
            x.setVisible(true);
        });

                    return;
                }
            }
        }

        JOptionPane.showMessageDialog(null,
                "ID not found",
                "Error",
                JOptionPane.ERROR_MESSAGE);

    } catch (Exception e) {
        JOptionPane.showMessageDialog(null,
                "Error reading file!",
                "File Error",
                JOptionPane.ERROR_MESSAGE);
    }
}
}

