/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Customer;

import javax.swing.JOptionPane;




/**
 *
 * @author arsen
 */
public class LoyaltyAppGUI extends javax.swing.JFrame {


    private int customerId;
    private Order order;
    private Customer currentCustomer;

    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(LoyaltyAppGUI.class.getName());
    
    public LoyaltyAppGUI(int customerId) {
    this.customerId = customerId;
    initComponents();
    
    // Initialize labels as hidden
    ID_label.setVisible(false);
    name_label.setVisible(false);
    phone_label.setVisible(false);
    address_label.setVisible(false);
    totalSpent_label.setVisible(false);
    points_label.setVisible(false);
    orders_label.setVisible(false);
    
    // Initialize Order object
    order = new Order(); // Make sure Order class exists and has getTotalAmountByCustomerId method
    
    // Load customer - you need to implement Customer.getCustomerById()
    currentCustomer = Customer.getCustomerById(customerId);
    
    if (currentCustomer == null) {
        JOptionPane.showMessageDialog(this, "Customer not found with ID: " + customerId);
    }
}


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        prf_btn = new javax.swing.JButton();
        Rew_btn = new javax.swing.JButton();
        ID_label = new javax.swing.JLabel();
        name_label = new javax.swing.JLabel();
        phone_label = new javax.swing.JLabel();
        address_label = new javax.swing.JLabel();
        totalSpent_label = new javax.swing.JLabel();
        points_label = new javax.swing.JLabel();
        orders_label = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        prf_btn.setText("Profile");
        prf_btn.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        prf_btn.addActionListener(this::prf_btnActionPerformed);

        Rew_btn.setText("Rewards");
        Rew_btn.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        ID_label.setText("ID:");

        name_label.setText("Name:");

        phone_label.setText("Phone number:");

        address_label.setText("Address:");

        totalSpent_label.setText("Total Spent:");

        points_label.setText("Loyalty points:");

        orders_label.setText("Total Orders:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(Rew_btn, javax.swing.GroupLayout.PREFERRED_SIZE, 242, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(ID_label, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addComponent(name_label, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(phone_label, javax.swing.GroupLayout.DEFAULT_SIZE, 254, Short.MAX_VALUE))
                        .addContainerGap())
                    .addComponent(address_label, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(totalSpent_label, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(points_label, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(orders_label, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(prf_btn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(prf_btn)
                    .addComponent(Rew_btn))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(ID_label)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(name_label)
                .addGap(18, 18, 18)
                .addComponent(phone_label)
                .addGap(18, 18, 18)
                .addComponent(address_label)
                .addGap(18, 18, 18)
                .addComponent(totalSpent_label)
                .addGap(18, 18, 18)
                .addComponent(points_label)
                .addGap(18, 18, 18)
                .addComponent(orders_label)
                .addContainerGap(77, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void prf_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_prf_btnActionPerformed
         if (currentCustomer == null) {
            JOptionPane.showMessageDialog(this, "No customer loaded!");
            return;
        }

        // Set label text from currentCustomer
        ID_label.setText("ID: " + currentCustomer.getCustID());
        name_label.setText("Name: " + currentCustomer.getName());
        phone_label.setText("Phone: " + currentCustomer.getPhoneNum());
        address_label.setText("Address: " + currentCustomer.getAddress());
        totalSpent_label.setText("Total Spent: " + order.getTotalAmountByCustomerId(currentCustomer.getCustID()));
        points_label.setText("Loyalty Points: " + currentCustomer.getLoyaltyPoints());
        orders_label.setText("Total Orders: " + Customer.countOrdersByCustomer(customerId));

        // Make labels visible
        ID_label.setVisible(true);
        name_label.setVisible(true);
        phone_label.setVisible(true);
        address_label.setVisible(true);
        totalSpent_label.setVisible(true);
        points_label.setVisible(true);
        orders_label.setVisible(true);
    
    }//GEN-LAST:event_prf_btnActionPerformed

    /**
     * @param args the command line arguments
     */
       public static void main(String args[]) {
        // Example: normally this is called from the registration GUI
        java.awt.EventQueue.invokeLater(() -> new LoyaltyAppGUI(1).setVisible(true));
    
       }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel ID_label;
    private javax.swing.JButton Rew_btn;
    private javax.swing.JLabel address_label;
    private javax.swing.JLabel name_label;
    private javax.swing.JLabel orders_label;
    private javax.swing.JLabel phone_label;
    private javax.swing.JLabel points_label;
    private javax.swing.JButton prf_btn;
    private javax.swing.JLabel totalSpent_label;
    // End of variables declaration//GEN-END:variables
}
